apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
    spec:
      serviceAccountName: cheese-account
      containers:
      - name: cheese
        image: docker.io/yngus4862/cheese:1.8
        ports:
        - containerPort: 8888
