apiVersion: apps/v1
kind: Deployment
metadata:
  name: cheese
  labels:
    app: cheese
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cheese
  template:
    metadata:
      labels:
        app: cheese
    spec:
      serviceAccountName: cheese-account
      containers:
      - name: cheese
        image: docker.io/yngus4862/cheese:1.8
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: cheese
  name: cheese
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
    nodePort: 30001
  selector:
    name: cheese
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cheese-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cheese-account-system-admin
subjects:
- kind: ServiceAccount
  name: cheese-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
